name: github pages

on:
  push:
    branches:
      - master
  workflow_dispatch: null

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: true # could be useful in the future
          fetch-depth: 0   # we just need the latest commit

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v2
        with:
          mdbook-version: '0.5.2'

      - name: Install mdbook-mermaid
        run: cargo install mdbook-mermaid --version 0.17.0 --locked

      - name: Build mdbook
        working-directory: ./cookbook
        run: mdbook build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        if: github.ref == 'refs/heads/master'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./cookbook/book
